import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:zentory_app/objectbox.g.dart'; // This will be generated by the user later

class ObjectBoxDatabase {
  late final Store store;

  ObjectBoxDatabase._create(this.store);

  static Future<ObjectBoxDatabase> create() async {
    final docsDir = await getApplicationDocumentsDirectory();
    final store =
        await openStore(directory: p.join(docsDir.path, "zentory_db"));
    return ObjectBoxDatabase._create(store);
  }
}
