// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/database/entities.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5991102671533116898),
    name: 'MovementLocal',
    lastPropertyId: const obx_int.IdUid(11, 3159579916682292548),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4150287746650643923),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5180443220634092185),
        name: 'remoteId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 7089794931370486804),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3642027525140688254),
        name: 'workspaceId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1149371139303423928),
        name: 'productId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8262708977047218626),
        name: 'productName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7626015974085201230),
        name: 'quantity',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 79636336642514655),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6964738370067914558),
        name: 'reason',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8632292603440704377),
        name: 'createdBy',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 7501464946676142117),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 3159579916682292548),
        name: 'isPendingSync',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 6354520800334229834),
    name: 'ProductLocal',
    lastPropertyId: const obx_int.IdUid(12, 1611084169214218842),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4944234678553732757),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7280284079880775952),
        name: 'remoteId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 8495323698979060418),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 682742972693397643),
        name: 'workspaceId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 595062585260363639),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1719182273660927102),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8457193049716438255),
        name: 'price',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4766403145737117236),
        name: 'stock',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5239318236455436071),
        name: 'imageUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 3715577876349271730),
        name: 'category',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 9153733183600159444),
        name: 'lastSync',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 1611084169214218842),
        name: 'isPendingSync',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 6354520800334229834),
    lastIndexId: const obx_int.IdUid(2, 8495323698979060418),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [796150647617244718],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    MovementLocal: obx_int.EntityDefinition<MovementLocal>(
      model: _entities[0],
      toOneRelations: (MovementLocal object) => [],
      toManyRelations: (MovementLocal object) => {},
      getId: (MovementLocal object) => object.id,
      setId: (MovementLocal object, int id) {
        object.id = id;
      },
      objectToFB: (MovementLocal object, fb.Builder fbb) {
        final remoteIdOffset = fbb.writeString(object.remoteId);
        final workspaceIdOffset = fbb.writeString(object.workspaceId);
        final productIdOffset = fbb.writeString(object.productId);
        final productNameOffset = fbb.writeString(object.productName);
        final typeOffset = fbb.writeString(object.type);
        final reasonOffset = object.reason == null
            ? null
            : fbb.writeString(object.reason!);
        final createdByOffset = fbb.writeString(object.createdBy);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, remoteIdOffset);
        fbb.addOffset(2, workspaceIdOffset);
        fbb.addOffset(3, productIdOffset);
        fbb.addOffset(4, productNameOffset);
        fbb.addFloat64(5, object.quantity);
        fbb.addOffset(6, typeOffset);
        fbb.addOffset(7, reasonOffset);
        fbb.addOffset(8, createdByOffset);
        fbb.addInt64(9, object.createdAt.millisecondsSinceEpoch);
        fbb.addBool(10, object.isPendingSync);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final remoteIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final workspaceIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final productIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final productNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final quantityParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final reasonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final createdByParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
        );
        final isPendingSyncParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          24,
          false,
        );
        final object = MovementLocal(
          remoteId: remoteIdParam,
          workspaceId: workspaceIdParam,
          productId: productIdParam,
          productName: productNameParam,
          quantity: quantityParam,
          type: typeParam,
          reason: reasonParam,
          createdBy: createdByParam,
          createdAt: createdAtParam,
          isPendingSync: isPendingSyncParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    ProductLocal: obx_int.EntityDefinition<ProductLocal>(
      model: _entities[1],
      toOneRelations: (ProductLocal object) => [],
      toManyRelations: (ProductLocal object) => {},
      getId: (ProductLocal object) => object.id,
      setId: (ProductLocal object, int id) {
        object.id = id;
      },
      objectToFB: (ProductLocal object, fb.Builder fbb) {
        final remoteIdOffset = fbb.writeString(object.remoteId);
        final workspaceIdOffset = fbb.writeString(object.workspaceId);
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = fbb.writeString(object.description);
        final imageUrlOffset = object.imageUrl == null
            ? null
            : fbb.writeString(object.imageUrl!);
        final categoryOffset = object.category == null
            ? null
            : fbb.writeString(object.category!);
        fbb.startTable(13);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, remoteIdOffset);
        fbb.addOffset(2, workspaceIdOffset);
        fbb.addOffset(3, nameOffset);
        fbb.addOffset(4, descriptionOffset);
        fbb.addFloat64(5, object.price);
        fbb.addInt64(6, object.stock);
        fbb.addOffset(7, imageUrlOffset);
        fbb.addOffset(9, categoryOffset);
        fbb.addInt64(10, object.lastSync.millisecondsSinceEpoch);
        fbb.addBool(11, object.isPendingSync);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final remoteIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final workspaceIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final priceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final stockParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final imageUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final categoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final lastSyncParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0),
        );
        final isPendingSyncParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          26,
          false,
        );
        final object = ProductLocal(
          remoteId: remoteIdParam,
          workspaceId: workspaceIdParam,
          name: nameParam,
          description: descriptionParam,
          price: priceParam,
          stock: stockParam,
          imageUrl: imageUrlParam,
          category: categoryParam,
          lastSync: lastSyncParam,
          isPendingSync: isPendingSyncParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [MovementLocal] entity fields to define ObjectBox queries.
class MovementLocal_ {
  /// See [MovementLocal.id].
  static final id = obx.QueryIntegerProperty<MovementLocal>(
    _entities[0].properties[0],
  );

  /// See [MovementLocal.remoteId].
  static final remoteId = obx.QueryStringProperty<MovementLocal>(
    _entities[0].properties[1],
  );

  /// See [MovementLocal.workspaceId].
  static final workspaceId = obx.QueryStringProperty<MovementLocal>(
    _entities[0].properties[2],
  );

  /// See [MovementLocal.productId].
  static final productId = obx.QueryStringProperty<MovementLocal>(
    _entities[0].properties[3],
  );

  /// See [MovementLocal.productName].
  static final productName = obx.QueryStringProperty<MovementLocal>(
    _entities[0].properties[4],
  );

  /// See [MovementLocal.quantity].
  static final quantity = obx.QueryDoubleProperty<MovementLocal>(
    _entities[0].properties[5],
  );

  /// See [MovementLocal.type].
  static final type = obx.QueryStringProperty<MovementLocal>(
    _entities[0].properties[6],
  );

  /// See [MovementLocal.reason].
  static final reason = obx.QueryStringProperty<MovementLocal>(
    _entities[0].properties[7],
  );

  /// See [MovementLocal.createdBy].
  static final createdBy = obx.QueryStringProperty<MovementLocal>(
    _entities[0].properties[8],
  );

  /// See [MovementLocal.createdAt].
  static final createdAt = obx.QueryDateProperty<MovementLocal>(
    _entities[0].properties[9],
  );

  /// See [MovementLocal.isPendingSync].
  static final isPendingSync = obx.QueryBooleanProperty<MovementLocal>(
    _entities[0].properties[10],
  );
}

/// [ProductLocal] entity fields to define ObjectBox queries.
class ProductLocal_ {
  /// See [ProductLocal.id].
  static final id = obx.QueryIntegerProperty<ProductLocal>(
    _entities[1].properties[0],
  );

  /// See [ProductLocal.remoteId].
  static final remoteId = obx.QueryStringProperty<ProductLocal>(
    _entities[1].properties[1],
  );

  /// See [ProductLocal.workspaceId].
  static final workspaceId = obx.QueryStringProperty<ProductLocal>(
    _entities[1].properties[2],
  );

  /// See [ProductLocal.name].
  static final name = obx.QueryStringProperty<ProductLocal>(
    _entities[1].properties[3],
  );

  /// See [ProductLocal.description].
  static final description = obx.QueryStringProperty<ProductLocal>(
    _entities[1].properties[4],
  );

  /// See [ProductLocal.price].
  static final price = obx.QueryDoubleProperty<ProductLocal>(
    _entities[1].properties[5],
  );

  /// See [ProductLocal.stock].
  static final stock = obx.QueryIntegerProperty<ProductLocal>(
    _entities[1].properties[6],
  );

  /// See [ProductLocal.imageUrl].
  static final imageUrl = obx.QueryStringProperty<ProductLocal>(
    _entities[1].properties[7],
  );

  /// See [ProductLocal.category].
  static final category = obx.QueryStringProperty<ProductLocal>(
    _entities[1].properties[8],
  );

  /// See [ProductLocal.lastSync].
  static final lastSync = obx.QueryDateProperty<ProductLocal>(
    _entities[1].properties[9],
  );

  /// See [ProductLocal.isPendingSync].
  static final isPendingSync = obx.QueryBooleanProperty<ProductLocal>(
    _entities[1].properties[10],
  );
}
